"""``hawcx wrap`` — generate tool wrappers from a ``hawcx/agent-template/v1``.

Auto-wrap plan U1. Replaces the hand-copied ``_HawcxToolBase`` that the CrewAI
and LangChain demos each carry: that copy is what this deletes.

THREE RULES THIS GENERATOR OBEYS
--------------------------------
1. **Never rewrite developer files** (plan §1). It emits ONE new module and
   never touches existing sources. The developer imports it. An AST rewriter
   would have to be re-run on every edit and would own the developer's file.

2. **Generate from ``tools[].{id, actions}`` only.** Not ``constraints``, not
   ``suggested_levels`` — those are suggestions, and a suggestion compiled into
   a shipped artifact starts behaving like a control. Enforced structurally:
   the generator is handed :func:`hawcx_haap.template.tool_entries`' narrow
   projection and cannot reach a field it was never given.

3. **No endpoints in generated code.** Endpoints, providers and bearers come
   from the org tool registry / EIB at runtime (Pattern Z), so the generated
   classes take ``endpoint`` at construction from a deployment-supplied map.
   The template stays a description; the URL map stays plumbing.

FRAMEWORK-NEUTRAL ON PURPOSE
----------------------------
The emitted classes are plain callables over ``HawcxAgent.invoke``, not CrewAI
or LangChain subclasses. Both frameworks can adapt a callable (CrewAI via
``hawcx_crewai.HawcxTool``, LangChain via ``StructuredTool.from_function``),
whereas a framework-specific emitter would need one code path per framework and
a hard dependency on each. ``framework.kind`` in the template still drives the
*docstring* and the adapter hint, so nothing is lost.
"""

from __future__ import annotations

import datetime as _dt
import keyword
import re
from typing import Any, Iterable

from .template import tool_entries

__all__ = ["generate_module", "class_name_for", "GenerationError"]

_BANNER = "# @generated by `hawcx wrap` — DO NOT EDIT. Regenerate from the template."


class GenerationError(Exception):
    """Raised when a valid template still cannot be turned into code."""


def class_name_for(tool_id: str) -> str:
    """``o365.group.add_member`` -> ``O365GroupAddMemberTool``.

    Deterministic, because generated output is committed by some teams and a
    non-deterministic name would show up as spurious diff churn.
    """
    parts = [p for p in re.split(r"[._]+", tool_id) if p]
    name = "".join(p[:1].upper() + p[1:] for p in parts) + "Tool"
    if not name[:1].isalpha():
        # A tool id may legally start with a digit (`[a-z0-9_]+`), which is not a
        # legal Python identifier. Prefix rather than drop, so two ids that
        # differ only in a leading digit cannot collide into one class.
        name = "Tool" + name
    if keyword.iskeyword(name):  # unreachable today; cheap insurance
        name += "_"
    return name


def _check_collisions(entries: Iterable[tuple[str, tuple[str, ...]]]) -> None:
    """Distinct tool ids must yield distinct class names.

    ``a.b_c`` and ``a.b.c`` both normalise to ``ABCTool``. Silently emitting one
    class for two tools would make the second tool's calls carry the first
    tool's identity — an authorization bug produced by a naming convention, so
    fail closed instead of disambiguating with a counter (a counter makes the
    mapping depend on declaration order).
    """
    seen: dict[str, str] = {}
    for tid, _ in entries:
        cls = class_name_for(tid)
        if cls in seen and seen[cls] != tid:
            raise GenerationError(
                f"tool ids {seen[cls]!r} and {tid!r} both generate class {cls!r} — "
                "rename one in the template; the generator will not disambiguate "
                "automatically because the mapping would then depend on order"
            )
        seen[cls] = tid


def generate_module(doc: dict[str, Any], *, source_path: str = "<template>",
                    stamp_time: bool = False) -> str:
    """Return the source of the generated wrapper module."""
    entries = tool_entries(doc)
    _check_collisions(entries)
    name = doc["name"]
    version = doc["version"]
    framework = (doc.get("framework") or {}).get("kind", "unknown")

    # Off by default: a timestamp makes byte-identical regeneration impossible,
    # so `hawcx wrap` in CI would show a diff on every run. Opt in when a
    # human-readable provenance line is worth more than reproducibility.
    stamp = ""
    if stamp_time:
        stamp = f"\n# Generated at {_dt.datetime.now(_dt.timezone.utc).isoformat(timespec='seconds')}"

    lines: list[str] = [
        _BANNER,
        f"# template : {name} {version}  ({source_path})",
        f"# framework: {framework}",
        f"# tools    : {len(entries)}" + stamp,
        '"""HAAP-wrapped tools for `' + name + '`.',
        "",
        "Every call goes through `HawcxAgent.invoke`, so the agent process never",
        "holds a reusable credential: the Assembler mints a per-call token and",
        "performs the provider-credential fetch out of process.",
        "",
        "`endpoint` is a constructor argument, NOT template data — endpoints come",
        "from the org tool registry / EIB at runtime (Pattern Z). Nothing below",
        "`tools:` in the template reached this file; `constraints` and",
        "`suggested_levels` are suggestions and are applied by policy, not code.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from hawcx_haap import HawcxAgent",
        "",
        "",
        "class _HawcxGeneratedTool:",
        '    """Base for every generated tool. One HAAP tool identity per class."""',
        "",
        "    TOOL_ID: str = \"\"",
        "    ACTIONS: tuple[str, ...] = ()",
        "",
        "    def __init__(self, agent: HawcxAgent, endpoint: str, *,",
        "                 method: str = \"POST\", provider: str | None = None,",
        "                 acting_for_user: str | None = None) -> None:",
        "        if not self.TOOL_ID:",
        "            raise ValueError(\"_HawcxGeneratedTool is abstract; use a generated subclass\")",
        "        if not endpoint:",
        "            # Fail closed. An empty endpoint would reach the Assembler as an",
        "            # empty target and surface as an opaque mint/forward error far",
        "            # from the missing registry entry that actually caused it.",
        "            raise ValueError(",
        "                f\"{type(self).__name__}: endpoint is required — resolve it from the \"",
        "                f\"org tool registry for tool id {self.TOOL_ID!r}\"",
        "            )",
        "        self._agent = agent",
        "        self._endpoint = endpoint",
        "        self._method = method",
        "        self._provider = provider",
        "        self._acting_for_user = acting_for_user",
        "",
        "    @property",
        "    def tool_id(self) -> str:",
        "        return self.TOOL_ID",
        "",
        "    def __call__(self, **arguments: Any):",
        "        \"\"\"Invoke the tool. Keyword arguments become the tool arguments.\"\"\"",
        "        return self._agent.invoke(",
        "            target_rs_url=self._endpoint,",
        "            http_method=self._method,",
        "            tool=self.TOOL_ID,",
        "            action=self.ACTIONS,",
        "            provider=self._provider,",
        "            acting_for_user=self._acting_for_user,",
        "            tool_arguments=arguments or None,",
        "        )",
        "",
    ]

    for tid, actions in entries:
        cls = class_name_for(tid)
        acts = ", ".join(repr(a) for a in actions)
        lines += [
            "",
            f"class {cls}(_HawcxGeneratedTool):",
            f'    """`{tid}` — actions: {", ".join(actions)}."""',
            "",
            f'    TOOL_ID = "{tid}"',
            f"    ACTIONS = ({acts}{',' if len(actions) == 1 else ''})",
            "",
        ]

    # A registry keyed by tool id, so a deployment can drive construction from
    # its endpoint map instead of importing each class by name.
    lines += [
        "",
        "#: Tool id -> generated class. Keyed by the HAAP tool identity, not by",
        "#: class name, because the tool id is what policy and the Assembler bind to.",
        "TOOLS: dict[str, type[_HawcxGeneratedTool]] = {",
    ]
    for tid, _ in entries:
        lines.append(f'    "{tid}": {class_name_for(tid)},')
    lines += [
        "}",
        "",
        "",
        "def build_tools(agent: HawcxAgent, endpoints: dict[str, str], **kwargs: Any):",
        '    """Construct every tool from an id -> endpoint map.',
        "",
        "    Raises on an endpoint map that does not cover the template, rather than",
        "    silently building a partial tool set: a missing tool shows up later as",
        "    the agent simply never attempting that call, which looks like a model",
        "    decision rather than a configuration gap.",
        '    """',
        "    missing = sorted(set(TOOLS) - set(endpoints))",
        "    if missing:",
        "        raise ValueError(f\"no endpoint supplied for: {missing}\")",
        "    extra = sorted(set(endpoints) - set(TOOLS))",
        "    if extra:",
        "        # Fail closed too: an endpoint for a tool the template does not",
        "        # declare means the map and the template disagree about scope.",
        "        raise ValueError(f\"endpoint supplied for undeclared tool(s): {extra}\")",
        "    return {tid: cls(agent, endpoints[tid], **kwargs) for tid, cls in TOOLS.items()}",
        "",
    ]
    return "\n".join(lines)
