"""``hawcx wrap`` -- generate tool wrappers from a ``hawcx/agent-template/v1``.

Auto-wrap plan U1. Replaces the hand-copied ``_HawcxToolBase`` that the CrewAI
and LangChain demos each carry: that copy is what this deletes.

THREE RULES THIS GENERATOR OBEYS
--------------------------------
1. **Never rewrite developer files** (plan §1). It emits ONE new module and
   never touches existing sources. The developer imports it. An AST rewriter
   would have to be re-run on every edit and would own the developer's file.

2. **Generate from ``tools[].{id, actions}`` only.** Not ``constraints``, not
   ``suggested_levels`` — those are suggestions, and a suggestion compiled into
   a shipped artifact starts behaving like a control. Enforced structurally:
   the generator is handed :func:`hawcx_haap.template.tool_entries`' narrow
   projection and cannot reach a field it was never given.

3. **No endpoints in generated code.** Endpoints, providers and bearers come
   from the org tool registry / EIB at runtime (Pattern Z), so the generated
   classes take ``endpoint`` at construction from a deployment-supplied map.
   The template stays a description; the URL map stays plumbing.

FRAMEWORK-NEUTRAL ON PURPOSE
----------------------------
The emitted classes are plain callables over ``HawcxAgent.invoke``, not CrewAI
or LangChain subclasses. Both frameworks can adapt a callable (CrewAI via
``hawcx_crewai.HawcxTool``, LangChain via ``StructuredTool.from_function``),
whereas a framework-specific emitter would need one code path per framework and
a hard dependency on each. ``framework.kind`` in the template still drives the
*docstring* and the adapter hint, so nothing is lost.
"""

from __future__ import annotations

import datetime as _dt
import keyword
import re
from collections.abc import Iterable
from typing import Any

from .template import tool_entries

__all__ = ["generate_module", "generate_config", "class_name_for", "GenerationError"]

# ASCII ONLY, and this is a correctness constraint rather than a style rule.
# Generated source is written and re-read by other tools, and `Path.write_text`
# / `open()` without an explicit encoding use the PLATFORM DEFAULT — cp1252 on
# Windows. An em-dash in this banner round-tripped through cp1252 becomes byte
# 0x97, and Python then refuses to import its own generated module with
# "SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x97".
#
# Found on the Windows CI matrix, passing on ubuntu and macOS. Emitting pure
# ASCII removes the entire class rather than requiring every current and future
# reader to remember `encoding="utf-8"`. `assert_ascii` below enforces it, so a
# future edit that reintroduces a smart quote fails loudly at generation time.
_BANNER = "# @generated by `hawcx wrap` -- DO NOT EDIT. Regenerate from the template."


class GenerationError(Exception):
    """Raised when a valid template still cannot be turned into code."""


def class_name_for(tool_id: str) -> str:
    """``o365.group.add_member`` -> ``O365GroupAddMemberTool``.

    Deterministic, because generated output is committed by some teams and a
    non-deterministic name would show up as spurious diff churn.
    """
    parts = [p for p in re.split(r"[._]+", tool_id) if p]
    name = "".join(p[:1].upper() + p[1:] for p in parts) + "Tool"
    if not name[:1].isalpha():
        # A tool id may legally start with a digit (`[a-z0-9_]+`), which is not a
        # legal Python identifier. Prefix rather than drop, so two ids that
        # differ only in a leading digit cannot collide into one class.
        name = "Tool" + name
    if keyword.iskeyword(name):  # unreachable today; cheap insurance
        name += "_"
    return name


def _check_collisions(entries: Iterable[tuple[str, tuple[str, ...]]]) -> None:
    """Distinct tool ids must yield distinct class names.

    ``a.b_c`` and ``a.b.c`` both normalise to ``ABCTool``. Silently emitting one
    class for two tools would make the second tool's calls carry the first
    tool's identity — an authorization bug produced by a naming convention, so
    fail closed instead of disambiguating with a counter (a counter makes the
    mapping depend on declaration order).
    """
    seen: dict[str, str] = {}
    for tid, _ in entries:
        cls = class_name_for(tid)
        if cls in seen and seen[cls] != tid:
            raise GenerationError(
                f"tool ids {seen[cls]!r} and {tid!r} both generate class {cls!r} — "
                "rename one in the template; the generator will not disambiguate "
                "automatically because the mapping would then depend on order"
            )
        seen[cls] = tid


def _assert_ascii(source: str) -> str:
    """Refuse to emit non-ASCII source. See the `_BANNER` comment for why.

    Raises rather than transliterating: a silent substitution would put a
    character in the developer's file that they did not write and cannot find in
    the template.
    """
    non_ascii = sorted({c for c in source if ord(c) > 127})
    if non_ascii:
        raise GenerationError(
            "refusing to emit non-ASCII generated source "
            f"({', '.join(f'{c!r} (U+{ord(c):04X})' for c in non_ascii)}). "
            "Generated modules are read back by tools that may not specify an "
            "encoding, and the platform default is cp1252 on Windows. Use ASCII."
        )
    return source


def generate_module(doc: dict[str, Any], *, source_path: str = "<template>",
                    stamp_time: bool = False) -> str:
    """Return the source of the generated wrapper module. Always ASCII."""
    entries = tool_entries(doc)
    _check_collisions(entries)
    name = doc["name"]
    version = doc["version"]
    framework = (doc.get("framework") or {}).get("kind", "unknown")

    # Off by default: a timestamp makes byte-identical regeneration impossible,
    # so `hawcx wrap` in CI would show a diff on every run. Opt in when a
    # human-readable provenance line is worth more than reproducibility.
    stamp = ""
    if stamp_time:
        now = _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")
        stamp = f"\n# Generated at {now}"

    lines: list[str] = [
        _BANNER,
        f"# template : {name} {version}  ({source_path})",
        f"# framework: {framework}",
        f"# tools    : {len(entries)}" + stamp,
        '"""HAAP-wrapped tools for `' + name + '`.',
        "",
        "Every call goes through `HawcxAgent.invoke`, so the agent process never",
        "holds a reusable credential: the Assembler mints a per-call token and",
        "performs the provider-credential fetch out of process.",
        "",
        "`endpoint` is a constructor argument, NOT template data -- endpoints come",
        "from the org tool registry / EIB at runtime (Pattern Z). Nothing below",
        "`tools:` in the template reached this file; `constraints` and",
        "`suggested_levels` are suggestions and are applied by policy, not code.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from hawcx_haap import HawcxAgent",
        "",
        "",
        "class _HawcxGeneratedTool:",
        '    """Base for every generated tool. One HAAP tool identity per class."""',
        "",
        "    TOOL_ID: str = \"\"",
        "    ACTIONS: tuple[str, ...] = ()",
        "",
        "    def __init__(self, agent: HawcxAgent, endpoint: str, *,",
        "                 method: str = \"POST\", provider: str | None = None,",
        "                 acting_for_user: str | None = None) -> None:",
        "        if not self.TOOL_ID:",
        "            raise ValueError(",
        "                \"_HawcxGeneratedTool is abstract; use a generated subclass\"",
        "            )",
        "        if not endpoint:",
        "            # Fail closed. An empty endpoint would reach the Assembler as an",
        "            # empty target and surface as an opaque mint/forward error far",
        "            # from the missing registry entry that actually caused it.",
        "            raise ValueError(",
        "                f\"{type(self).__name__}: endpoint is required -- resolve it from the \"",
        "                f\"org tool registry for tool id {self.TOOL_ID!r}\"",
        "            )",
        "        self._agent = agent",
        "        self._endpoint = endpoint",
        "        self._method = method",
        "        self._provider = provider",
        "        self._acting_for_user = acting_for_user",
        "",
        "    @property",
        "    def tool_id(self) -> str:",
        "        return self.TOOL_ID",
        "",
        "    def __call__(self, **arguments: Any):",
        "        \"\"\"Invoke the tool. Keyword arguments become the tool arguments.\"\"\"",
        "        return self._agent.invoke(",
        "            target_rs_url=self._endpoint,",
        "            http_method=self._method,",
        "            tool=self.TOOL_ID,",
        "            action=self.ACTIONS,",
        "            provider=self._provider,",
        "            acting_for_user=self._acting_for_user,",
        "            tool_arguments=arguments or None,",
        "        )",
        "",
    ]

    for tid, actions in entries:
        cls = class_name_for(tid)
        acts = ", ".join(repr(a) for a in actions)
        lines += [
            "",
            f"class {cls}(_HawcxGeneratedTool):",
            f'    """`{tid}` -- actions: {", ".join(actions)}."""',
            "",
            f'    TOOL_ID = "{tid}"',
            f"    ACTIONS = ({acts}{',' if len(actions) == 1 else ''})",
            "",
        ]

    # A registry keyed by tool id, so a deployment can drive construction from
    # its endpoint map instead of importing each class by name.
    lines += [
        "",
        "#: Tool id -> generated class. Keyed by the HAAP tool identity, not by",
        "#: class name, because the tool id is what policy and the Assembler bind to.",
        "TOOLS: dict[str, type[_HawcxGeneratedTool]] = {",
    ]
    for tid, _ in entries:
        lines.append(f'    "{tid}": {class_name_for(tid)},')
    lines += [
        "}",
        "",
        "",
        "def build_tools(agent: HawcxAgent, endpoints: dict[str, str], **kwargs: Any):",
        '    """Construct every tool from an id -> endpoint map.',
        "",
        "    Raises on an endpoint map that does not cover the template, rather than",
        "    silently building a partial tool set: a missing tool shows up later as",
        "    the agent simply never attempting that call, which looks like a model",
        "    decision rather than a configuration gap.",
        '    """',
        "    missing = sorted(set(TOOLS) - set(endpoints))",
        "    if missing:",
        "        raise ValueError(f\"no endpoint supplied for: {missing}\")",
        "    extra = sorted(set(endpoints) - set(TOOLS))",
        "    if extra:",
        "        # Fail closed too: an endpoint for a tool the template does not",
        "        # declare means the map and the template disagree about scope.",
        "        raise ValueError(f\"endpoint supplied for undeclared tool(s): {extra}\")",
        "    return {tid: cls(agent, endpoints[tid], **kwargs) for tid, cls in TOOLS.items()}",
        "",
    ]
    return _assert_ascii("\n".join(lines))


# ── `hawcx init`: the customer-owned config ──────────────────────────────────
#
# Issue #88. Once the Lane A core (`Caller`/`Decision`/allow-deny
# classification) lives in the SDK, the only thing a customer still hand-writes
# is their deployment config: which MCP tools exist, where they are, and which
# principals the agent may act for. Every customer writing that from scratch is
# how a fleet ends up with N subtly different shapes of the same file, which is
# the copy-paste dynamic `hawcx wrap` was built to retire.
#
# Same input, second output — so it lives beside `generate_module` and reuses
# `tool_entries`. Rule 2 above still holds: the config generator is handed the
# same narrow `(id, actions)` projection and cannot reach `constraints` or
# `suggested_levels` either.
#
# TWO OUTPUTS, OPPOSITE OWNERSHIP. `generate_module` emits `@generated -- DO NOT
# EDIT`, regenerated freely. This emits a file the customer edits and keeps.
# That is why `hawcx init` writes them under different rules (`--force`
# regenerates the module; nothing overwrites the config) rather than `hawcx wrap
# --config` writing both under one flag: one `--force` governing a generated
# module and a hand-edited config would eventually eat somebody's config while
# they were doing the routine thing to the module.

_CONFIG_BANNER = (
    "# Scaffolded by `hawcx init`. THIS FILE IS YOURS -- edit it and keep it.\n"
    "# Nothing regenerates over your edits: `hawcx init` refuses to overwrite an\n"
    "# existing config.py, so re-running it after adding tools to the template\n"
    "# rewrites the generated tool module and leaves this file alone."
)


def generate_config(doc: dict[str, Any], *, source_path: str = "<template>") -> str:
    """Return the source of a customer-owned ``config.py``. Always ASCII.

    Every deployment-specific value is emitted as ``FILL_ME``, and the module
    ends in a :func:`~hawcx_haap.mcp_caller.require_filled` call, so an
    unfilled config raises at **import** naming every gap at once. A commented
    placeholder would have read as configured and reached the Assembler as a
    real target; this cannot.

    What is NOT emitted, and why:

    * **HTTP method.** MCP ``tools/call`` over Streamable HTTP is POST, and
      :meth:`Caller.invoke_kwargs` sets it. A knob whose only correct value is
      the default is a knob someone eventually turns.
    * **Per-tool provider.** :class:`~hawcx_haap.mcp_caller.Caller` carries one
      ``provider`` for the destination it talks to, so ``PROVIDER`` is one
      value here. An agent spanning two providers builds two ``Caller``s.
    * **Endpoints as data from the template.** Same Pattern Z rule as
      :func:`generate_module`: URLs come from the org tool registry / EIB, so
      the template never carried one and neither does this file.
    """
    entries = tool_entries(doc)
    # Class names are irrelevant to this file, but a template that cannot
    # produce a module must not quietly produce half a scaffold either: the two
    # outputs of `hawcx init` succeed or fail together.
    _check_collisions(entries)
    name = doc["name"]
    version = doc["version"]

    lines: list[str] = [
        _CONFIG_BANNER,
        f"# template: {name} {version}  ({source_path})",
        '"""Deployment config for `' + name + '`.',
        "",
        "Fill in every FILL_ME below. Until you do, importing this module raises a",
        "ValueError naming every value still unfilled -- an unfilled deployment",
        "fails here rather than sending a placeholder somewhere as a URL or a",
        "principal.",
        "",
        "Use it like::",
        "",
        "    from hawcx_haap import Caller, close_agent, get_agent",
        "",
        "    import config",
        "",
        "    def run(principal: str) -> None:",
        "        caller = Caller(agent=get_agent(config.PRINCIPAL_ALLOWLIST),",
        "                        provider=config.PROVIDER)",
        "        try:",
        "            for tool in config.TOOLS.values():",
        "                print(caller.call(tool, principal).summary())",
        "        finally:",
        "            close_agent()",
        "",
        "`principal` comes from the request being served; PRINCIPAL_ALLOWLIST is what",
        "decides whether it is permitted. Those are two different things and the",
        "second one is not derived from the first.",
        "",
        "Pure-Python and stdlib-only apart from `hawcx_haap` itself, so an agent",
        "carrying this file still bundles with `hawcx bundle` (a zipapp cannot",
        "carry native extensions).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from hawcx_haap import FILL_ME, McpTool, require_filled",
        "",
        "#: OAuth provider id naming the bridging bearer the Assembler attaches for",
        "#: this destination, e.g. \"microsoft\". Write None if this agent needs no",
        "#: bridging bearer -- write it explicitly, because \"no provider\" and \"nobody",
        "#: has looked at this yet\" must not be the same value.",
        "PROVIDER: str | None = FILL_ME",
        "",
        "#: The principals this agent may act for. REQUIRED, and deliberately",
        "#: without a default: it is the fail-closed gate on `acting_for_user`, so a",
        "#: default here would be a default answer to \"who may this agent",
        "#: impersonate\". Source it from operator config -- NEVER from model output,",
        "#: a request body, or anything an LLM can influence.",
        "#:",
        "#: `[]` is a real answer and means \"forbid runtime principal switching",
        "#: entirely\". It is not the same as leaving this unfilled.",
        "PRINCIPAL_ALLOWLIST: list[str] = FILL_ME",
        "",
        "#: HAAP tool id -> the MCP tool it names. `tool_id` and `actions` come from",
        "#: the template and are already filled; `url`, `name` and `resource` are",
        "#: yours, because only your tenant knows them.",
        "#:",
        "#: `name` is the downstream MCP tool name from the server's own",
        "#: `tools/list` -- not the HAAP tool id, and not a guess at it. Enumerate",
        "#: the tenant's MCP inventory and paste the real names in.",
        "TOOLS: dict[str, McpTool] = {",
    ]

    for tid, actions in entries:
        acts = ", ".join(repr(a) for a in actions)
        lines += [
            f'    "{tid}": McpTool(',
            f'        tool_id="{tid}",',
            "        url=FILL_ME,        # target RS URL of the MCP server",
            "        name=FILL_ME,       # downstream MCP tool name from tools/list",
            f"        actions=({acts}{',' if len(actions) == 1 else ''}),",
            "        resource=FILL_ME,   # resource scope, or \"*\" for the whole server",
            "    ),",
        ]

    lines += [
        "}",
        "",
        "# Fails the import while any FILL_ME survives, naming every one of them in",
        "# one message. Keep this call: it is the difference between a placeholder",
        "# that stops a deployment and a placeholder that ships in one.",
        "require_filled(",
        "    PROVIDER=PROVIDER,",
        "    PRINCIPAL_ALLOWLIST=PRINCIPAL_ALLOWLIST,",
        "    TOOLS=TOOLS,",
        ")",
        "",
    ]
    return _assert_ascii("\n".join(lines))
